### ISSUE TITLE
Can't install (with brew) on older than Sonoma

### ISSUE THREAD

**Issue by nicocossiom** [FelixKratz/JankyBorders#10]
I got the following when trying to install via brew on an M1 MBPro on macOS Ventura 13.6.1:
```bash
$ brew install borders

borders: This software does not run on macOS versions older than Sonoma.
Error: borders: An unsatisfied requirement failed this build.
```

So I built the binary manually and it works completely fine. Posting so requirements for the brew formulae are relaxed, at least for Ventura which is quite recent.

Also, this works very well, I was missing borders from yabai. Thank you!

**Comment by kkreso** [comment]
I tried it, it does work but with strange always visible overlapping borders.
 
<img width="1415" alt="image" src="https://github.com/FelixKratz/JankyBorders/assets/12595159/ef043b0b-a9fe-4ecc-8ed2-825c4d4a6f50">

**Comment by FelixKratz** [comment]
I no longer have a Ventura machine I can test the software with and since the APIs used here are prone to deprecations and changes between macOS version it is probably best to focus on Sonoma for now.

**Comment by FelixKratz** [comment]
> I tried it, it does work but with strange always visible overlapping borders.
> 
> <img alt="image" width="1415" src="https://user-images.githubusercontent.com/12595159/280410109-ef043b0b-a9fe-4ecc-8ed2-825c4d4a6f50.png">

Could you try the following: remove the line
```c
  SLSWindowManagementBridgeSetDelegate(NULL);
```
from `main.c` and try running the binary again and see if the strange ordering persists.

**Comment by kkreso** [comment]
> ```c
> SLSWindowManagementBridgeSetDelegate(NULL);
> ```

Tried, issue is still there. I appreciate your efforts, the borders really help differentiate the windows and make things easier to use. I'll upgrade to Sonoma probably just because of the JankyBorders.

**Comment by nicocossiom** [comment]
@kkreso you're right, since I use yabai I rarely have two windows stacked hence why I didn't see the overlapping borders. Will update to Sonoma in some time once it's more stable and use Janky Borders. Thank you for looking into this!

**Comment by archaengel** [comment]
For posterity -- setting `inactive_color=00000000` is a workaround to get rid of this issue for folks still on Ventura

**Comment by nicocossiom** [comment]
> For posterity -- setting `inactive_color=00000000` is a workaround to get rid of this issue for folks still on Ventura

can confirm this does in did fix the issue. Thank you very much, pretty clever solution
