### ISSUE TITLE
apply-to=<window-id> configuration ignores default config behavior after invoked

### ISSUE THREAD

**Issue by aspauldingcode** [FelixKratz/JankyBorders#101]
After using the feature implemented from #57, I use a command to set the borders style=round or style=square for toggling gaps.
However, after toggling fullscreen on then back off (with another custom script that uses apply-to=<window-id> for hiding the border), the custom toggle-gaps command only applies to the windows which didn't invoke apply-to=<window-id>. 

Maybe there's a way to reset the border invocation of `apply-to=<window-id>` like `reset=<window-id>`, so that it continues to work with regular borders commands that don't use `apply-to=<window-id>`.

**Comment by FelixKratz** [comment]
Lets discuss this further in #57
