### ISSUE TITLE
Move Alpha Channel to end of hex code?

### ISSUE THREAD

**Issue by kyldvs** [FelixKratz/JankyBorders#102]
It's strange to me that the alpha channel for colors is at the start (`0xAARRGGBB`), almost everywhere I've ever seen hexcodes the 8-digit version has alpha at the end (`0xRRGGBBAA`) [source](https://developer.mozilla.org/en-US/docs/Web/CSS/hex-color).

I spent half an hour going crazy trying to figure out why JankyBorders' colors were "just wrong" when it was my fault for writing them in the wrong format. It didn't cross my mind that it would be in a non-standard hexcode format. (This is mostly on me for not thoroughly reading the man pages).

I think an improvement would be to either move alpha to the end, or add a line to the readme about the specific `0xAARRGGBB` format. I thought the documentation in the README was sufficient to get going, but I was wrong.

Thanks for the tool either way, now that it's working I'm enjoying it a lot!

**Comment by FelixKratz** [comment]
There are several counter-examples in the macOS desktop customisation application family:

* https://github.com/FelixKratz/SketchyBar (Which is by me, so thats a slight bias)
* https://github.com/koekeishiya/yabai
