### ISSUE TITLE
Show the border only where there are multiple windows on the screen

### ISSUE THREAD

**Issue by munjyong** [FelixKratz/JankyBorders#103]
Is it possible to configure this to show the border only where there are multiple windows on the screen? Because I only need to see the border to identify which window is currently active out of `x`.

<img width="1728" alt="image" src="https://github.com/FelixKratz/JankyBorders/assets/40276401/b1ba545b-5002-4dc2-8e57-3a67f82a33e2">

<img width="1728" alt="image" src="https://github.com/FelixKratz/JankyBorders/assets/40276401/d1a97069-b907-41f7-b503-e4659ebdb496">

**Comment by FelixKratz** [comment]
See #53
