### ISSUE TITLE
Does not render blur or background when order=above

### ISSUE THREAD

**Issue by aspauldingcode** [FelixKratz/JankyBorders#105]
the only part that is never working is the background_color and the blur_radius.
In addition, to get it to work from a command, I have to kill borders first and then invoke the command args.

```
#!/bin/bash

options=(
  style=round
  order=above
  width=2.0
  background_color=0x1132302f
  blur_radius=15.0
  hidpi=on
  active_color=0xfffbf1c7
  inactive_color=0xffd5c4a1
  blacklist="google chrome,vmware fusion,xQuartz,dmenu-mac,X11.bin,MacForge"
)

borders "${options[@]}"
```

**Comment by aspauldingcode** [comment]
ahh. Works when I toggle gaps off.
I think its because I set in my shell toggle-gaps would place borders above, then when gaps off borders are below. Does borders really onlly render the background and blur when it is set to below?

Can we fix this?

**Comment by Bellavene** [comment]
https://github.com/FelixKratz/JankyBorders/issues/78

**Comment by FelixKratz** [comment]
It is an undocumented and unsupported option.
