### ISSUE TITLE
allow me to specify order=above without affecting background blur

### ISSUE THREAD

**Issue by aspauldingcode** [FelixKratz/JankyBorders#109]
if you allow borders order=above, I can have square application windows that will be rounded when floating.
If you remove the background blur, then invoking order=above will just remove the background blur.

if you specifically only tell the border around the window to be above the window, and remain the rest of the features behind it, we could get borders that look like swayfx windows, actually. 

Current implementation is going to be a problem, even if I want to make a second instance of borders to do this it doesn't work because I can't run more than one instance of borders.

**Comment by aspauldingcode** [comment]
Yes I understand order=above is a non-documented feature, but visually it fixes so many issues on my end with 1:1 UI between my macOS rice and my linux rice.

**Comment by FelixKratz** [comment]
I am myself not using the `order=above` option. However, it is a very simple code change and I would be open for a pull request. The background blur has severe performance problems and will be removed in the next release (see #78)
