### ISSUE TITLE
Options aren't working

### ISSUE THREAD

**Issue by hegedusgergely** [FelixKratz/JankyBorders#116]
First of all, thanks for JankyBorders! This is exactly what I was looking for! 

My issue is that seemingly no matter what I put into the `bordersrc` file it has no affect on borders.
1. I've installed JankyBorders (1.6) via Brew and I run it with `brew services start borders`.
2. I've created a `bordersrc` file under `~/.config/borders/` and updated the `hidpi` and `width` values.
3. Restarted borders with `brew services restart borders` (tried stop and start as well) and I can see no change in borders width or hairiness whatsoever.
4. I expected the width and sharpness to be updated after the restart of the service.
![Screenshot 2024-09-07 at 17 45 59@2x](https://github.com/user-attachments/assets/7e495244-ee2a-4eea-bf2b-e43f35253974)
I'm on macOS 14.6.1

**Comment by lewisdenny** [comment]
Hey, exact same versions as you and working for me.

Some things you could check are the log files(mine are empty but maybe you have something):
```
/opt/homebrew/var/log/borders/borders.err.log
/opt/homebrew/var/log/borders/borders.out.log
```

Can you share your config file?

Can you verify your config file permissions, here are mine:
```
$ ll .config/borders/bordersrc
.rwxr--r-- 173 ldenny 10 Sep 14:22  .config/borders/bordersrc
```

Hopefully something there helps, one last thing is maybe you ran `borders` manually outside `brew` in another terminal and that instance is what your seeing.

**Comment by hegedusgergely** [comment]
Hey @lewisdenny,

Thanks for the reply!

It was the file permissions. Changed to 754 and borders is working as expected. My issue is solved now.

**Comment by lewisdenny** [comment]
> Hey @lewisdenny,
> 
> Thanks for the reply!
> 
> It was the file permissions. Changed to 754 and borders is working as expected. My issue is solved now.

Wonderful, great to hear :)
