### ISSUE TITLE
Feature suggesstion: Use color format as RRGGBBAA

### ISSUE THREAD

**Issue by danielcs88** [FelixKratz/JankyBorders#120]
Hi, this works wonders with Aerospace. A small suggestion: It would be easier to use RRGGBBAA rather than AARRGGBB, as color picker websites use this convention (e.g., https://rgbacolorpicker.com/rgba-to-hex), and even color picker extensions on VS Code.

The active color I chose was pink shade, however in the code editor it appears as green.

<img width="785" alt="image" src="https://github.com/user-attachments/assets/82c6de96-023d-4ff6-916d-df3fb9d375e1">

**Comment by FelixKratz** [comment]
See #102
