### ISSUE TITLE
[Feature Request] Can we run borders in multiple instance like SketchyBar?

### ISSUE THREAD

**Issue by cxa** [FelixKratz/JankyBorders#136]
Because I need to use different style for some specific applications, like:

```sh
borders "${args[@]}" blacklist="app_name"
borders2 "${args2[@]}" whitelist="app_name"
```

**Comment by FelixKratz** [comment]
Technically yes, that would be possible. Wouldn't #57 together with a window manager script be more appropriate?

**Comment by cxa** [comment]
Nice, archived with `apply-to`, thanks!
