### ISSUE TITLE
Firefox and Firefox-based browsers cause border flickering order=above

### ISSUE THREAD

**Issue by 1seco** [FelixKratz/JankyBorders#141]
While in order=below, no border flickering is found with any window. With order=above, border flickering is only found within Firefox/Firefox-based browsers, and triggered on any input: mouse clicks, keys clicked.

https://github.com/user-attachments/assets/24ffe52e-cb06-4617-97a8-63532b6eea9e

**Comment by FelixKratz** [comment]
order=above is unsupported and undocumented.

**Comment by Mirage-Panda** [comment]
I think it is because of Firefox constantly fighting for the top layer when there is keyboard input.

**Comment by Bellavene** [comment]
> I think it is because of Firefox constantly fighting for the top layer when there is keyboard input.

Close, because the address input field is messing up the "new window" signal, e.g., spawns on any change. If you are using yabai, this should be manageable by excluding all other window types for Firefox, except normal windows [This issue](https://github.com/koekeishiya/yabai/issues/2515) and [this one](https://github.com/FelixKratz/JankyBorders/issues/66) are related.

Check the role and subrole of the browsers windows.
```
yabai -m query --windows | jq -re '.[] | select(."app"== "Browser Name").id'
```
Exclude the unneeded ones like this
```
yabai -m rule --add app="^Chrome.*$" \
         role="AXLayoutArea" \
         subrole="AXFloatingWindow" \
         manage=off
```

**Comment by danielsvane** [comment]
@Bellavene do you know of a workaround for aerospace too?

**Comment by Bellavene** [comment]
> [@Bellavene](https://github.com/Bellavene) do you know of a workaround for aerospace too?

Sorry, but I don't have experience with aerospace, so I can't help with it. Better to look at the aerospace repo. There should be issues about it.

**Comment by MokitoSama** [comment]
I just opened an issue related to this one with aerospace, maybe yabai could be a better fit for me too. I just noticed the issue doesn't persist in other windows other than the browsers and ones that constantly fight for the top

**Comment by ELLIOTTCABLE** [comment]
@MokitoSama I cannot find any such issue on the AeroSpace repo, nor do I see the backlink to mentioned/related issue here - could you drop a link in here?
