### ISSUE TITLE
Safari: border disappears on link hover

### ISSUE THREAD

**Issue by kinglouie** [FelixKratz/JankyBorders#16]
Just installed JankyBorders and noticed that the border around safari browser disappears as soon as I hover a link an a website. 
Maybe this is because safari creates some kind of window for displaying the link target url in the bottom left corner?

**Comment by FelixKratz** [comment]
I see what the problem is. I think I have am idea how to fix it.

**Comment by FelixKratz** [comment]
Should be fixed.

**Comment by kinglouie** [comment]
Nice that was really fast 😊
