### ISSUE TITLE
Old windows seem to be unbordered

### ISSUE THREAD

**Issue by prdanelli** [FelixKratz/JankyBorders#2]
First of all, thank you for trying to fill the gap left by Yabai's border removal. 

I added the following to my `.yabairc`: 

```
borders active_color=0xffffffff inactive_color=0xff494d64 width=5.0 2>/dev/null 1>&2 &
```

I noticed something with windows created before yabai started. 

![image](https://github.com/FelixKratz/JankyBorders/assets/1199977/4adfc657-b204-4a67-ba5c-5e59c05bfdce)

The main window on the left was already created, and used to start yabai. Then once it was running, I created the windows on the right. When I use the command `opt+k/j/l` to move between windows, the two new windows seem to have the border correctly, but when I refocus on the older existing window, the border doesn't get added. 

As you can see from the image above, the window on the left has the MacOS drop shadow, signifying that it is currently focused, but the white border is on the bottom right window.

**Comment by FelixKratz** [comment]
Yes, this is still a TODO. But it will be implemented in the future. If you are starting yabai as a service on launch and bootstrap the borders exe to yabai it should not be that big of a problem for now, which is why I decided to release it even though this is not implemented yet.

**Comment by prdanelli** [comment]
Thank you @FelixKratz.

**Comment by FelixKratz** [comment]
I will keep this opened to remind myself to work on it some time soon.

**Comment by FelixKratz** [comment]
v1.0.2 contains this due to a pull request.
