### ISSUE TITLE
[Docs] Do not know how to deactivate or update active color after enable using yabai

### ISSUE THREAD

**Issue by harrylowkey** [FelixKratz/JankyBorders#21]
Thank you very much for this plugin, I see it's so cool but I'm facing some issues, can you please check it?

After enable for yabai followed by the command in the docs:
`active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 2>/dev/null 1>&2 &`

I do not know how to set to another color, try to set again like the command below but it not work:
`active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 2>/dev/null 1>&2 &`

Also if I want to disable it I just don't know how to do it event running the command: `brew uninstall borders`
Can you please update the README.md also the docs for the `man` command, thank you!

**Comment by FelixKratz** [comment]
Try using this command:
```bash
borders active_color=0xff00ff00
```
It will set the active border color to green.

If you want to stop the brew service run:
```bash
brew services stop borders
```
or if you ran it from somewhere else and you want to terminate the process just use:
```bash
killall borders
```
