### ISSUE TITLE
[Request] Option to have high res window borders

### ISSUE THREAD

**Issue by emilknievel** [FelixKratz/JankyBorders#24]
Hi,

I have noticed that the borders are a bit "blurry". I think there was an option in yabai when it had borders integrated that allowed us to select more high resolution rendering.

I have attached an image below that shows what I'm talking about.

Best regards.

<img width="84" alt="bild" src="https://github.com/FelixKratz/JankyBorders/assets/1216268/12ac3499-e13c-4037-84e4-2ad4b5090f64">

**Comment by FelixKratz** [comment]
I mainly chose to default to 1x scale on the borders to save memory and cpu time when redrawing, but it is of course trivial to change the resolution to 2x scale here possibly with an option:
https://github.com/FelixKratz/JankyBorders/blob/09ec9196570fe9e25ce788bfbcc3399d3c1cee78/src/helpers.h#L227

**Comment by emilknievel** [comment]
Totally.

I just made the mistake of looking too closely and thus I can't unsee the fuzz 🙈

**Comment by emilknievel** [comment]
Tried it out from --HEAD and it works like a charm. Thank you.
