### ISSUE TITLE
Borders stop updating when move to newly created space

### ISSUE THREAD

**Issue by albert-ying** [FelixKratz/JankyBorders#25]
```
ctrl + alt + shift - n : yabai -m space --create && \
                  index="$(yabai -m query --spaces --display | jq 'map(select(.))[-1].index')" && \
                  yabai -m window --space "${index}" && \
                  yabai -m space --focus "${index}" 
```

I have this in my skhd. After this command, the border for the given window stop updating (size and color)

**Comment by albert-ying** [comment]
moving window to space itself is fine -- but somehow when the space is created by yabai, something goes wrong.

**Comment by FelixKratz** [comment]
If I run the command 
```bash
yabai -m space --create && \
                  index="$(yabai -m query --spaces --display | jq 'map(select(.))[-1].index')" && \
                  yabai -m window --space "${index}" && \
                  yabai -m space --focus "${index}"
```
from a kitty window it seems to work fine. Can you try to narrow down the problem more? I.e. try to run the command from your terminal directly with only one monitor etc.

**Comment by albert-ying** [comment]
https://share.cleanshot.com/jghCmg

This is the screen recording. The second condition gives the same result...

**Comment by albert-ying** [comment]
> Did you unload the WindowManager process? If so, stop doing so, reboot and test again

Oh yea -- it seems to be the reason! I had that in my .yabairc and after removing that and reloading, it works perfectly fine. Thank you!!!
