### ISSUE TITLE
Feature Request: Don't draw border for specific apps

### ISSUE THREAD

**Issue by parth-dt** [FelixKratz/JankyBorders#26]
Can we exclude certain apps while drawing the border? Yabai had that option and it is crucial for some apps to function in my setup.

For e.g. slack has a had time with huddle when border is on

**Comment by FelixKratz** [comment]
I think some kind of blacklist feature would be a good idea and should be easy to implement.

I.e. here we already have the application pid:
https://github.com/FelixKratz/JankyBorders/blob/ab4d6fce4b8fda3ae32c997dcab9e50118b5d864/src/windows.c#L14-L16
and could use it to get the process name and check a blacklist. If the blacklist hits, we simply return early.

Pull requests are welcome.

**Comment by PhrantiK** [comment]
If you just want to exclude a single app, this patch has been working for me to exclude the bloated mess Adobe Illustrator. Just need to change to Slack and it should work:

````
diff --git a/src/windows.c b/src/windows.c
index 7eb52ea..7e2e411 100644
--- a/src/windows.c
+++ b/src/windows.c
@@ -2,6 +2,7 @@
 #include "hashtable.h"
 #include <string.h>
 #include "border.h"
+#include <libproc.h>
 
 extern pid_t g_pid;
 
@@ -13,6 +14,14 @@ bool windows_window_create(struct table* windows, uint32_t wid, uint64_t sid) {
 
   pid_t pid = 0;
   SLSConnectionGetPID(wid_cid, &pid);
+
+	char process_name[PROC_PIDPATHINFO_MAXSIZE];
+    if (proc_name(pid, process_name, sizeof(process_name))) {
+        if (strcmp(process_name, "Adobe Illustrator") == 0) {
+            return false;
+        }
+    }
+
   if (pid == g_pid) return false;
 
   CFArrayRef target_ref = cfarray_of_cfnumbers(&wid,
````

**Comment by FelixKratz** [comment]
The blacklist functionality has been added on master, it works to following way:
```bash
borders blacklist="System Settings,Safari,kitty"
```
where a comma separated list of application names can be supplied. These are excluded from being bordered.

**Comment by parth-dt** [comment]
Thanks a lot @FelixKratz for this; it was a swift implementation :D

**Comment by diocletiann** [comment]
@FelixKratz I just installed with `--HEAD` and `borders blacklist="Sublime Text"` doesn't work. Am I missing something? Thanks for the awesome tool!

**Comment by wd** [comment]
It would be great to have a whitelist as well 😁
