### ISSUE TITLE
Render on top of application

### ISSUE THREAD

**Issue by jakenvac** [FelixKratz/JankyBorders#28]
Hi, thanks for the work on this project. I started my own borders tool since yabai dropped the feature but this one is far superior.

One thing I miss from my own tool, that I'd like to request is to have an option to allow borders render on top of the application. This is great for square borders as with a slightly thicker border you can have the illusion of square windows.

Here's an old screenshot that demonstrates what I mean:

![image](https://github.com/FelixKratz/JankyBorders/assets/9119973/8d526fb5-762f-4d17-9757-4ecf431048aa)

**Comment by jakenvac** [comment]
My borders tool was written in swift, so unfortunately I can't be much help with a solution right now as my c is very rusty.

**Comment by FelixKratz** [comment]
There are some more technical reasons why I think having borders on top of the window is not an option I want to pursue.

However, there already is an option for square borders included #11. They are square on the outside and rounded on the inside to make them fit all macOS windows. If your application, i.e. your terminal, allows to deactivate the corner mask, you can achieve square borders on the outside and inside.

**Comment by FelixKratz** [comment]
Some more details here: #37

**Comment by jakenvac** [comment]
Thanks for this! I know you were hesitant to add this feature but it's greatly appreciated. I appreciate all the hard work you've put into this project.
