### ISSUE TITLE
No available formula

### ISSUE THREAD

**Issue by Levvonci** [FelixKratz/JankyBorders#3]
Hi, i'm trying to install JankyBorders from brew, but after `brew install FelixKratz/formulae/borders` this is the output:
`Warning: No available formula or cask with the name "felixkratz/formulae/borders". Did you mean felixkratz/formulae/svim, felixkratz/formulae/fyabai or felixkratz/formulae/fnnn?`
I will clone the repository to compile it manually, I just created this issues to report the problem

**Comment by FelixKratz** [comment]
Try running: `brew update`, since the formula is pretty new.

**Comment by Levvonci** [comment]
> Try running: `brew update`, since the formula is pretty new. This should work if all else fails:
> 
> ```shell
> brew tap FelixKratz/formulae
> brew update
> brew install borders
> ```

it worked, but the borders don't seem to appear after putting the example `borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 2>/dev/null 1>&2 &` into yabairc

**Comment by FelixKratz** [comment]
Only new windows started after yabai will receive a border, see #2.
