### ISSUE TITLE
A lots of `borders - unknown` windows show in select list of zoom share screen

### ISSUE THREAD

**Issue by wd** [FelixKratz/JankyBorders#31]
I don't know if this is a problem from Zoom or borders, just bringing this up to see if there are some solutions. 

<img width="658" alt="image" src="https://github.com/FelixKratz/JankyBorders/assets/58177/fdf2340a-5360-41b9-93f5-6ceb973990ff">

**Comment by FelixKratz** [comment]
The window borders are windows afterall and if zoom chooses to display them as windows appropriate to share, we can not do anything about that. They should probably better filter the windows they display in that list based upon some window tags,
