### ISSUE TITLE
"Glowing" borders

### ISSUE THREAD

**Issue by koekeishiya** [FelixKratz/JankyBorders#32]
![image](https://github.com/FelixKratz/JankyBorders/assets/6175959/310d5597-4e66-461c-82cd-6c1743e8548f)

Source: https://www.reddit.com/r/unixporn/comments/w9s22b/hyprland_noble/

![image](https://github.com/FelixKratz/JankyBorders/assets/6175959/41571ffa-d783-48a7-a429-e933d457c85c)

Source: https://www.reddit.com/r/unixporn/comments/zqyrqi/hyprland_glowy/?rdt=34170

![image](https://github.com/FelixKratz/JankyBorders/assets/6175959/f0a6e0c8-c2a4-43e0-8653-e0d8d4854154)

(Bright spots are actually animated and moves around the border)

Source: https://www.reddit.com/r/unixporn/comments/17kx85t/hyprland_tokyo_night_nixos/?rdt=55754

--

I think this could look good when customized properly. Probably more useful for the active window than inactive ones. The static effect could likely be implemented by tweaking the border window shadow properties.

**Comment by FelixKratz** [comment]
Looks good. We could include this in the current configuration syntax as another special color argument e.g:
```bash
borders active_color=glow(0xAARRGGBB)
```
Or something like that.

I am still thinking about moving the drawing logic to a CALayer backed solution for GPU acceleration, where these animations could be included relatively easily, but I am not sure if that is worth the effort.

Maybe we start off with a static glow for now.

**Comment by FelixKratz** [comment]
I am not sure this can be achieved only by tweaking the window shadow properties, afaik there is no way to change the color of the shadow. I can change positioning density etc. via:
```c
extern CGError SLSSetWindowShadowParameters(int cid, uint32_t wid, float std, float density, int x_offset, int y_offset);
```
and there are some other properties to be controlled via
```c
extern CGError SLSWindowSetShadowProperties(uint32_t wid, CFDictionaryRef properties);
```
but I have not seen a way to change the actual shadow color.

**Comment by FelixKratz** [comment]
I have added a subtle glow effect which can be actived by passing `glow(0xAARRGGBB)` to a `<color>` argument.

**Comment by Bellavene** [comment]
Was trying to instal through --HEAD, and borders broke. They render somewhere outside the window.

**Comment by FelixKratz** [comment]
Possibly because of this commit: https://github.com/FelixKratz/JankyBorders/commit/e629ff3c3b27d2c83805793042d94e36fc0321d4
Will revert it later…

**Comment by FelixKratz** [comment]
I will at some point explore simple animations on window focus/unfocus, but a permanently moving glow around the border is probably not something I am personally interested in.

If someone wants to give it a go, I will gladly accept a PR.

**Comment by Bellavene** [comment]
Thanks. Nah, I don't want permanently moving glow neither.

**Comment by Bellavene** [comment]
**An attempt to animate**

```
#!/bin/zsh
borders active_color='gradient(top_left=0xffffa100,bottom_right=0xffaa0033)' \
        inactive_color='gradient(top_left=0xaa00a100,bottom_right=0x550000aa)' \
        ax_focus=on width=8 \
        order=above \
        background_color=0x00000000 \
        2>/dev/null 1>&2 &
        # style=square \
        # blur_radius=30.0 \
sleep 0.07
borders active_color='glow(0xffff5100)' 2>/dev/null 1>&2 &
sleep 0.07
borders active_color='glow(0xffff0000)' 2>/dev/null 1>&2 &
sleep 0.07
borders active_color='glow(0xffff5100)' 2>/dev/null 1>&2 &
sleep 0.07
borders active_color='gradient(top_left=0xffffa100,bottom_right=0xffaa0033)' 2>/dev/null 1>&2 &

```
