### ISSUE TITLE
Different border color for some window types

### ISSUE THREAD

**Issue by crisidev** [FelixKratz/JankyBorders#35]
Hello,
I was wondering if you could be interested in a feature that allows to specify the border color for different type of windows:
* active
* floating
* fullscreen

When the window is focused, the border can change depending on the window type, with a config like this one:

```sh
options=(
    active_color="0xAABBCCDDEEFF"
    float_color="0xAABBCCDDEEFF"
    fullscreen_color="0xAABBCCDDEEFF"
)

borders "${options[@]}"
```

What do you think?

**Comment by FelixKratz** [comment]
Hi,
since it is possible to change the active border color at any point in time by calling:
```bash
borders active_color=0xAARRGGBB
```
you could already script this by using yabai events. So I dont think it is needed to compile this into the binary.

**Comment by crisidev** [comment]
Ah, true, its a good idea, thanks. I'll close this and add some example code once I have it working.
