### ISSUE TITLE
All border drawn when changing spaces

### ISSUE THREAD

**Issue by amusingimpala75** [FelixKratz/JankyBorders#39]
Whenever I am changing spaces, but most noticeably when swiping between spaces (it's just to fast when using keybinds) JB draws border for all windows regardless of display during the switching process.
Normally looks like:
<img width="1680" alt="Screenshot 2023-12-16 at 11 43 46 AM" src="https://github.com/FelixKratz/JankyBorders/assets/69653100/e7f5f9e0-745a-41ad-8628-788d293f8bd9">
But specifically while changing spaces, it temporarily looks like:
![Screenshot 2023-12-16 at 11 43 03 AM](https://github.com/FelixKratz/JankyBorders/assets/69653100/97900de8-720b-4580-aae4-f1b92aa85e90)

It's especially evident when transitioning to/from an empty desktop or one with transparent windows, and there is another desktop split by yabai for two windows:
![Screenshot 2023-12-16 at 11 48 11 AM](https://github.com/FelixKratz/JankyBorders/assets/69653100/9dfa9735-0881-469b-bf62-37a0ff21c9d6)
(The center line should not be there)

Any idea why?

**Comment by deusipse** [comment]
I have the same problem too! Very visible when swiping (three finger swipe) to change spaces from empty desktop:
<img width="1440" alt="image" src="https://github.com/FelixKratz/JankyBorders/assets/69350438/8d01b696-4433-43ca-91ce-5825ee1adf4c">

**Comment by FelixKratz** [comment]
Should be fixed on master.
