### ISSUE TITLE
Feature Request: "Allow list"

### ISSUE THREAD

**Issue by vkhitrin** [FelixKratz/JankyBorders#41]
I was wondering if there is an interest in having an "invert" of the blacklist.
For example, by default, borders will not be drawn for any application, and users will have to opt in to have borders drawn individually.

Thank you for this great piece of software @FelixKratz!

**Comment by FelixKratz** [comment]
Thats a good idea, I have added this on master as a `whitelist` that works exactly like the current `blacklist` but of course only apps listed in the whitelist (and not listed in the blacklist) will receive a border.
