### ISSUE TITLE
Slowdown when using for a while requiring a restart

### ISSUE THREAD

**Issue by kabeersvohra** [FelixKratz/JankyBorders#42]
Hi @FelixKratz 

Thank you for all your work. It really is nice to have these features due to your hard work.

I have been experiencing slowdown issues while using JankyBorders and after uninstalling it last night my M2 Pro machine is running fast again. It seems like the same issue as in this issue, hence why borders were removed from Yabai v6:

https://github.com/koekeishiya/yabai/issues/1775

Have you been experiencing this issue and is there a solution to it?

Thanks

**Comment by FelixKratz** [comment]
Hi,

do you experience this slowdown even when yabai is not running? Because the slowdown from the issue you have linked is caused by APIs that I am not using at all.

**Comment by kabeersvohra** [comment]
Yes I notice it when using yabai. I can try to turn off yabai and see if the slowdown starts to occur. Strangely enough I also notice it when using MS teams screen share as that also draws a border around the window I am sharing. Is this not something you have experienced with your version of yabai?

**Comment by kabeersvohra** [comment]
The slowdown often occurs when typing that it takes some seconds between the keypress and being registered. I have re-enabled the borders for now and will try to record it when it next slows down.

**Comment by kabeersvohra** [comment]
so it just happened again, I killed both yabai and borders and it was completely unrelated :(, thanks for your help, closing this ticket
