### ISSUE TITLE
bordersrc must be executable

### ISSUE THREAD

**Issue by xav-ie** [FelixKratz/JankyBorders#43]
Idk if I am just dumb but I was trying for a couple of days on and off and could not figure out why my bordersrc file was not working until I found out it must be executable. Is that obvious? Regardless, simply having this as a searchable issue should hopefully help someone. :)

Maybe add a little one-liner to readme? starting the service does not say anything...

**Comment by FelixKratz** [comment]
I am trying to make the config file executable if it is not executable from the binary in this function:
https://github.com/FelixKratz/JankyBorders/blob/69e733ce0499712f17e2fa676b64206b1b5e452b/src/helpers.h#L43-L51

So in theory you should not need to manually change the executable permissions, as long as the borders process has permissions to change the executable bit of the config file. I have now included a more verbose error message if this fails.
