### ISSUE TITLE
[Feature Request] Fill space beneath window

### ISSUE THREAD

**Issue by evgkirov** [FelixKratz/JankyBorders#48]
Is it possible to make JankyBorders not only draw borders around a window but also filling the rectangle space beneath it?

This enhancement would enable the option to apply a tint to the translucent parts of an active window, providing a more visually appealing (to some) alternative to the current wallpaper 'bleed-through' effect

<details><summary>Here's now</summary>
<p>
<img width="1800" alt="Screenshot 2024-01-12 at 21 11 38" src="https://github.com/FelixKratz/JankyBorders/assets/208751/889671f1-909d-44f1-9b1e-e6d0d259702e">
<img width="1800" alt="Screenshot 2024-01-12 at 21 14 04" src="https://github.com/FelixKratz/JankyBorders/assets/208751/dadc3ed0-3e78-43d9-9125-81185f6db294">
</p>
</details> 

<details><summary>Here's how it could look</summary>
<p>
<img width="1800" alt="Screenshot 2024-01-12 at 21 12 47" src="https://github.com/FelixKratz/JankyBorders/assets/208751/4f2e2aca-7938-4599-9d4b-5948e160008e">
<img width="1800" alt="Screenshot 2024-01-12 at 21 14 28" src="https://github.com/FelixKratz/JankyBorders/assets/208751/58215391-cd66-437b-98d7-5bb4ccdfe1e5">

</p>
</details>

**Comment by FelixKratz** [comment]
This is added on current master, where the background color can be set through:
```bash
borders background_color=<color>
```
currently only plain `0xAARRGGBB` colors are supported for background. Additionally, you can control the blur radius applied to the background via:
```bash
borders blur_radius=<float>
```
