### ISSUE TITLE
Add to README intro

### ISSUE THREAD

**Issue by rowdyrotifer** [FelixKratz/JankyBorders#49]
> It enhances the user experience [...] without relying on the accessibility API

Could you add a little sentence-blurb here describing how the software _does_ achieve its functionality? 😄

ty!

**Comment by FelixKratz** [comment]
What exactly do you mean? Do you have anything specific in mind?

**Comment by rowdyrotifer** [comment]
Sorry about forgetting to reply!  I could have been more clear.

I wasn't sure which API JankyBorders was using to achieve its functionality and I wanted to know. I couldn't really figure it out easily because I don't read a lot of C code.

I took a closer look through, and it seems like it relies on an API called "CoreGraphics", so basically my suggestion would be to say something like

> "[...] using CoreGraphics instead of relying on the accessibility API"

I think this is a useful piece of information because I kind of assumed that an app needs accessibility permissions in order to access window bounds on macOS.  I don't really know too much about macOS APIs but I think it could be useful thing to add to the readme.  Maybe it's immediately obvious to some people, but it wasn't to me.
