### ISSUE TITLE
Borders and Arc Browser PiP

### ISSUE THREAD

**Issue by JayFarei** [FelixKratz/JankyBorders#52]
I use Arc browser, which comes with a built in PiP window whenever you swap tabs on a running video feed.

When this feature is used with Borders, the border seem to wrap around much larger window than the PiP window itself, creating a visual glitch.

This used to cause issues with Yabai as well, but in v6.0.3 the issue was fixed ([Yabai #1622](https://github.com/koekeishiya/yabai/issues/1622))

The ideal behaviour is for Borders to ignore these windows natively similar to Yabai, alternatively offering a config based exclusion.

Note: in my set up Borders config is in the yabairc 
`borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 style=round &`

🙏

**Comment by FelixKratz** [comment]
You can disable this application by creating a `blacklist` entry for it. Then it will be excluded from being bordered.
