### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by amusingimpala75** [FelixKratz/JankyBorders#54]
On the latest version (and older ones as well), I noticed that according to btop, JankyBorders consumes almost 300MB of RAM, more than double what Emacs is using, and only less than Wezterm and Firefox. Is there anything inherent about the design of JB that results in such high memory consumption, or is this some sort of bug?

**Comment by FelixKratz** [comment]
I suspect you have `hidpi=on`. If you have a lot of high resolution windows the backing stores will consume considerable amounts of storage, there is no way around that in macOS. If you set `hidpi=off`, you should notice that the memory consumption in activity monitor decreases drastically.

**Comment by taylorthurlow** [comment]
`borders` was using more than 800MB ram until I turned this off, and its still over 100, which is surprising, but tolerable. I would honestly consider adding a disclaimer somewhere (perhaps I missed one), or even removing the option altogether.
