### ISSUE TITLE
Potential updates to window_suitable function

### ISSUE THREAD

**Issue by tbezman** [FelixKratz/JankyBorders#55]
I'd like to start by thanking you for this software. Really appreciate it.

While running JankyBorders, I noticed that some windows from the JetBrains suite are getting a border when ideally I think they would be ignored.

I cloned the codebase and searched around and found your `window_suitable` function. I'm really curious where you found documentation about these tags. I'd like to update the function to somehow ignore windows that are more "popup-esque" but I could not find any information about these tags on the internet.

I'd be happy to make the change myself if you could shed some light on these tags. If you're unable to provide information, I'll take some time to debug the attributes myself to see if there's any obvious flag that marks something as a popup window.

Here's a screenshot for reference:
![CleanShot 2024-01-31 at 20 20 05](https://github.com/FelixKratz/JankyBorders/assets/6754223/b9181f35-eb6d-48eb-b02c-0817d53adc45)

The "documentation" window on the right is technically focused at the time of taking this picture, but the border changing as the autocomplete window pops up and disappears while I'm typing can be quite jarring.

**Comment by FelixKratz** [comment]
I made some changes and further ignored all windows which are marked as being "attached" to some other window. Maybe this already solves the problem? If it doesn't, I have demystified the window tags a bit such that it is easier to update. The "documentation" of the window tag bits can be found here: https://github.com/NUIKit/CGSInternal/blob/master/CGSWindow.h
So if you want, you can have a go at it and see if you can improve the heuristic we apply in this function.

**Comment by tbezman** [comment]
I pulled down the latest main and it didn't work, for my own reference here's the tags for the popup window I want to ignore `0000001100000000000000000000000100000000000010000010000000001001`
