### ISSUE TITLE
Teams has no border

### ISSUE THREAD

**Issue by Hackmodford** [FelixKratz/JankyBorders#58]
For some reason a border is not drawn around the Microsoft Teams Classic app.

**Comment by kkreso** [comment]
Same thing for KeepassXC.

**Comment by FelixKratz** [comment]
Have a look at this function and see if you can improve the heuristic:
https://github.com/FelixKratz/JankyBorders/blob/2762982b93c58fb19b2f3e4570b145e701f121aa/src/misc/window.h#L5-L22
