### ISSUE TITLE
Border is moved to the active space

### ISSUE THREAD

**Issue by koekeishiya** [FelixKratz/JankyBorders#6]
So I noticed this weird bug that I can reproduce reliably, where a border that is initialized for an existing window on a different space upon launch will for some reason be moved back to the first/active space upon a window focus change event, as long as no other events have occurred. Edit: On commit https://github.com/FelixKratz/JankyBorders/commit/96534ddb78fc642a07e3143e3d81bf8b72ab5131

Basically, have two windows open on the active space, and have one window open on any alternate space.
Start *borders* and notice that you only get two borders drawn as expected. If you now switch focus to the other window in the same space, it suddenly drags the border belonging to the *alternate space window* and draws it on the active space.

If you create a new window first, and then focus a window, the bug does not occur.
I also verified that the border is actually moved properly after it is created by commenting out the responsible code in the *add_borders_for_existing_windows* function. When that move-call is removed, the border is drawn on the active space *all the time* (which one would expect).

 
![weird](https://github.com/FelixKratz/JankyBorders/assets/6175959/bc554304-f7d3-4251-b696-373e5b9f8608)

**Comment by FelixKratz** [comment]
I think this should fix the problem: https://github.com/FelixKratz/JankyBorders/commit/03c58ea29f31dbec03c0df287af96fa0fb06077c

**Comment by koekeishiya** [comment]
I made a local change that moved away from your `windows` and `borders` structs and replaced them with a single hashtable mapping from `wid` to `struct border` and the problem also went away. 
From a usage perspective it now also calls only `add_window` instead of having to call `add_window` followed by `add_border`.

Not sure these changes are compatible with your latest commit though.

**Comment by koekeishiya** [comment]
I inspected your commit and it does look like this particular change should solve this bug, yeah

```
  - border_draw(&borders->borders[borders->num_borders - 1]);
  + border_draw(border);
```

**Comment by FelixKratz** [comment]
You could post a PR with my latest commit reverted because it sounds like a nice improvement

**Comment by koekeishiya** [comment]
Opened a PR. The code is kinda low quality as it is kinda rushed so sorry about that, but tested and working.

**Comment by FelixKratz** [comment]
I think the PR has one major problem. When moving a window to a different space, there is a brief moment when two borders with the same wid exist, because the window is created at the target space first and then destroyed at the origin space. Thats why I used wid and sid checks to find the window.
This leads to the window "loosing" its space on the target space, because it is destroyed just after being created.

So my suggestion would be to use a has that is combined in some clever way from wid and sid to identify the window.

**Comment by koekeishiya** [comment]
I've confirmed that the current master with changes you made does fix this issue.
