### ISSUE TITLE
also supports macos 13 (not an issue just the readme shows macos 14+)

### ISSUE THREAD

**Issue by k2662** [FelixKratz/JankyBorders#63]
JankyBorders is a lightweight tool designed to add colored borders to user windows on macOS 14.0+. It enhances the user experience by visually highlighting the currently focused window without relying on the accessibility API, thereby being faster than comparable tools.

Suggested edit: JankyBorders is a lightweight tool designed to add colored borders to user windows on macOS 13.0+. It enhances the user experience by visually highlighting the currently focused window without relying on the accessibility API, thereby being faster than comparable tools.

**Comment by FelixKratz** [comment]
See #10. Maybe the problem of overlapping borders is fixed by the newest version? I have no machine I can test with for Ventura.

**Comment by k2662** [comment]
> See #10. Maybe the problem of overlapping borders is fixed by the newest version? I have no machine I can test with for Ventura.


Again, there isn't any issue with the borders (works just as expected) it just that saying macos 14+ is untrue.

**Comment by FelixKratz** [comment]
Brew will refuse to install on lower than sonoma https://github.com/FelixKratz/homebrew-formulae/blob/46d003101d8e8944a0efd2b108cd6463eecb61a5/borders.rb#L15 so thats why it says 14.0+. I have not put a version check in the actual code.
