### ISSUE TITLE
Inactive borders remains visible after using yabai makes window full screen

### ISSUE THREAD

**Issue by ArtemMosk** [FelixKratz/JankyBorders#65]
Not quite sure if it's border's issue or yabai but after upgrading yabai it looks like borders app keeps rendering both foreground and background borders after full-screen resize. Manual resizing (e.g., dragging borders with mouse) works fine. On screen yabai sends a resize signal somewhere (also active border reacts on full-screen resize).

<img width="3008" alt="image" src="https://github.com/FelixKratz/JankyBorders/assets/111910992/e15edb02-a08b-480d-b718-aa646c413cf4">

**Comment by FelixKratz** [comment]
are you running the latest version of borders? Because there was a fix for exactly that in the last version.
