### ISSUE TITLE
Border does not follow space when a window is sticky (using yabai)

### ISSUE THREAD

**Issue by koekeishiya** [FelixKratz/JankyBorders#67]
Title. The border appears to remain on space 1 for me, regardless of which space I use to open the application, and I can see the border window visible on space 1 when opening mission control.

How to reproduce:

Copy e.g youtube video to clipboard.

Use following bind from skhd:

```
shift + cmd - m : mpv $(pbpaste)
```

with following rule in yabai:
```
yabai -m rule --add app="^mpv$" manage=off sticky=on layer=above opacity=1.0 grid=8:8:6:0:2:2
```

Switch to e.g space 4, and back to space 3. Open mission control, or  just switch to space 1, and notice the border. Switch back to space 3 and the border is not there.

I can just use the blacklist feature to disable the border completely for mpv, so it is not a big deal.

**Comment by FelixKratz** [comment]
I have improved the handling of sticky windows in the code by making the border sticky as well depending on the window tag. I hope this fixes the problem.

**Comment by koekeishiya** [comment]
Can confirm, works fine after the latest changes.
