### ISSUE TITLE
Cant seem to get blur_radius to work

### ISSUE THREAD

**Issue by afridley** [FelixKratz/JankyBorders#69]
Im using
```
borders active_color=0xff3366ff inactive_color=0xff555555 width=3.0 blur_radius=30.0 &
```

But I don't seem to see my terminal blurred like what was happening when borders were in yabai.

Is the blur supported it seems to be referenced here

Am I missing something that needs to be added to signal that blur should be on

**Comment by FelixKratz** [comment]
You need to set a non-fully transparent background color, e.g.: `background_color=0x15ffffff`

**Comment by afridley** [comment]
Thank you worked perfectly
