### ISSUE TITLE
Temporal highlight

### ISSUE THREAD

**Issue by roeeyn** [FelixKratz/JankyBorders#72]
Hey! Thanks for your great tool. It could be great if it could be extended to support only a temporal highlight. Something similar to this [tool](https://github.com/dtinth/FocusHighlight.spoon). Do you think it's possible? Happy to help if needed :)

**Comment by FelixKratz** [comment]
You can already script something like this easily. Subscribe the the proper event in your window manager when a window is focused and then run this script:
```bash
borders active_color=0xffff0000
sleep 1
borders active_color=0x000000
```
If you want to be a little more fancy, you could place some intermediate alpha values separated by some more sleeps to make it look a bit smoother.
