### ISSUE TITLE
Bottom of the Border is not completely showing

### ISSUE THREAD

**Issue by JiggyMac12** [FelixKratz/JankyBorders#76]
I am having an issue to where the bottom of the border is visible, but is slightly tucked behind the window of the open app. 
![Screenshot 2024-03-10 at 11 31 03 AM](https://github.com/FelixKratz/JankyBorders/assets/146668871/7b2f5650-0c38-4bfa-914a-779467674233)

**Comment by FelixKratz** [comment]
Thats because the shadow of the window draws on top of the border, see #37 for more information about this.
