### ISSUE TITLE
Color of the inactive border differs on chromium

### ISSUE THREAD

**Issue by Bellavene** [FelixKratz/JankyBorders#8]
For some reason, the inactive border color of chromium based browsers differs from other windows. More clearly, it looks like the alpha channel is ignored.
<img width="172" alt="Screenshot 2023-11-03 at 13 06 25" src="https://github.com/FelixKratz/JankyBorders/assets/77557804/22915b38-db31-4755-bd86-7c3ebac70f7e">

**Comment by FelixKratz** [comment]
I think it is because of the window shadow. Do you use yabai to disable window shadow? If it is not window shadow I am not sure there is a way to fix this as it seems to be fully out of my control.

**Comment by Bellavene** [comment]
Shadows are disabled everywhere. I've looked more closely and it is not alpha channel, because the border is transparent. Got it.

**Comment by FelixKratz** [comment]
Maybe it is because there are two borders overlapping each other?
