### ISSUE TITLE
Border style fix

### ISSUE THREAD

**Issue by nithilgadde** [FelixKratz/JankyBorders#82]
Hello! 

Is it possible to get rid of the round corners when I enable the square borders?

<img width="169" alt="Screenshot 2024-04-04 at 5 44 12 PM" src="https://github.com/FelixKratz/JankyBorders/assets/110353659/505f3ad4-01f7-49a7-8e9b-f41257563928">

**Comment by 0xWaleed** [comment]
There is an option for style that you can pass to `borders`
https://github.com/FelixKratz/JankyBorders/blob/main/docs/borders.1.scd#options

**Comment by FelixKratz** [comment]
See https://github.com/FelixKratz/JankyBorders/issues/37#issuecomment-1877026340 for an unsupported and undocumented way to get truly square borders
