### ISSUE TITLE
Focused window different in borders and yabai

### ISSUE THREAD

**Issue by szfkamil** [FelixKratz/JankyBorders#84]
I use borders as an indicator of the active window for yabai. It's been working fine, but I noticed that sometimes the currently focused window per yabai is different from the active window by borders, such as after warping a stacked window. Is there a way to synchronise the currently focused window between the two?

**Comment by FelixKratz** [comment]
You could try to use `borders ax_focus=on` this should improve compatibility with certain yabai features.
