### ISSUE TITLE
Does it work with alacritty ?

### ISSUE THREAD

**Issue by maciej-gromul** [FelixKratz/JankyBorders#85]
In alacritty i'm getting shadows outside of the borders, do i need some specific setup for that ?  
![Screenshot 2024-04-12 at 08 44 25](https://github.com/FelixKratz/JankyBorders/assets/89904409/91aad99c-a104-4724-be5b-ce4ba17582d0)

**Comment by FelixKratz** [comment]
You can enable rounded borders in alacritty in its config
