### ISSUE TITLE
Brew install fails due to "framework not found AppKit"

### ISSUE THREAD

**Issue by KermityOwen** [FelixKratz/JankyBorders#87]
Full error here:

"""Last 15 lines from /Users/owenlee/Library/Logs/Homebrew/borders/01.make:
2024-04-20 17:47:24 +0000

make

mkdir bin
clang -std=c99 -O3 -g src/main.c src/parse.c src/mach.c src/hashtable.c src/events.c src/windows.c src/border.c src/animation.c  -o bin/borders -framework AppKit -framework CoreVideo -F/System/Library/PrivateFrameworks/ -framework SkyLight
ld: framework not found AppKit
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [all] Error 1"""

**Comment by FelixKratz** [comment]
AppKit is a core macOS framework. Your commandline tools installation might be bricked would be my guess
