### ISSUE TITLE
macOS Borders still visible 

### ISSUE THREAD

**Issue by niemes** [FelixKratz/JankyBorders#88]
Hi, love this project, thank you for all your efforts.

I was hoping to hide the macOS white border with the project but looks like the borders are drawn just around the windows and the macOS border are visible (**crying**)

Is there an **offset** option to hide those horrible white borders that would allow me to sleep in peace with my dark theme ? 

![Screenshot 2024-04-21 at 14 01 48](https://github.com/FelixKratz/JankyBorders/assets/6246777/55d4bbc3-ccf8-4a68-8248-6a7cef23af90)

_5px away from perfections_ 

Edit: 

After some digging if you change the border order to above, this will hide almost the system borders, but It's not totally perfect. The angles miss 1px in the curve of the corners, but It's not the end of the world.

`order=a`

Order above works almost perfectly, the flickering on Firefox is the only bad news, anyway. 

Case close I guess

**Comment by FelixKratz** [comment]
It is a technical limitation you can get around by using `yabai` to disable the window shadows.

**Comment by niemes** [comment]
> Did you ever find a solution to the border flickering in Firefox?

Not really :/, maybe try Zen Browser, Safari current version with UblockOrigin does a pretty good  job as a daily too.
