### ISSUE TITLE
Aborts immediately on start, Intel Mac OS Sonoma 14.1 

### ISSUE THREAD

**Issue by mrala** [FelixKratz/JankyBorders#9]
First off, thanks so much for taking on this project.

Please let me know what additional details would be useful to troubleshoot. I'm running on an Intel Mac, Sonoma 14.1 with SIP enabled. `borders` immediately crashes/aborts on start.

The only message I see is:

```
borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0
[1]    58275 abort      borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0
```

**Comment by FelixKratz** [comment]
Could  you try running:
```bash
brew update
brew upgrade borders
```
I think this problem is fixed in v1.1.1

**Comment by mrala** [comment]
No problems after upgrading to v1.1.1. Thanks!

**Comment by FelixKratz** [comment]
I think it was a memory layout coincidence that the previous code worked on arm macs, which is probably why all intel macs had instant abort: https://github.com/FelixKratz/JankyBorders/commit/ff11227f09356deae47ecfd679b2a519929482f8
