### ISSUE TITLE
Borders cannot be disabled on Firefox using blacklist

### ISSUE THREAD

**Issue by szfkamil** [FelixKratz/JankyBorders#91]
The borders for Firefox are not disabled after restarting the app, or the computer itself.

All the other apps are not displaying borders if blacklisted.

```
 blacklist="Firefox,Safari,System
 10         Preferences,System Settings,Calculator,Software
 11         Update,zoom.us,Photo Booth,Archive
 12         Utility,Python,LibeOffice,App Store,Activity Monitor,System
 13         Information,Print Centre,TextEdit,Disk Utility,Alfred Preferences,
 14         Alfred,Noi,Finder,Dictionary,Photos,Music,Spotify,VLC,Preview,Reminders,Todoist,Notes,iTerm2"
```

- I made sure it's not an issue of case-sensitivity.

**Comment by szfkamil** [comment]
I've re-installed the app and this has not fixed the issue.

**Comment by FelixKratz** [comment]
For me `borders blacklist="firefox"` seems to work just fine. It needs to be in lower case because the procname is `firefox` and not `Firefox`

**Comment by szfkamil** [comment]
> For me `borders blacklist="firefox"` seems to work just fine. It needs to be in lower case because the procname is `firefox` and not `Firefox`

Is this usual for an application name to be a different from process name? `man` says the name of the application.

The process name in activity monitor for Firefox is always upper-case. Unless by `procname` you mean something else?

![Screenshot 2024-04-28 at 20 23 39](https://github.com/FelixKratz/JankyBorders/assets/82778513/69c1c804-1fec-4d60-b1ad-a3128a6de041)

In any case, perhaps case-sensitive for app names would be a good feature request?
