### ISSUE TITLE
[Feature request] different color for maximized window

### ISSUE THREAD

**Issue by PavelSlepushkin** [FelixKratz/JankyBorders#92]
Is it possible to have different color for maximized window border? (add to active/inacative/ - maximized).
I know it can be scripted like 
```
if $(yabai -m query --windows --window |jq '."has-fullscreen-zoom"'); then 
	options=( first_options
	)
else
	options=( second_options
	)
fi

borders "${options[@]}"
```
But then this have to be set  on 'window_focused' event and borders are flickering on every focus change.
Or maybe there's some way to reduce flickering for re-configuration call?
PS - the goal is to have some indication for maximized window, and border color seems good option for that

**Comment by FelixKratz** [comment]
That will be possible once https://github.com/FelixKratz/JankyBorders/issues/57 is contained in the next release.
