### ISSUE TITLE
Borders are not centered

### ISSUE THREAD

**Issue by blaadje** [FelixKratz/JankyBorders#96]
Hi, thx for this amazing tool

Im having a little placement issue with borders since sonoma, where you can see a little gap on top of  **every** window (not only terminal) e.g
<img width="757" alt="image" src="https://github.com/FelixKratz/JankyBorders/assets/24897042/836bafc3-2f32-4d96-a809-8ab48bb3d3e3">

---

jankyBorders: 1.6.0
OS: Sonoma: 14.4.1
hardware: Apple M2 Pro

**Comment by FelixKratz** [comment]
I dont think thats a gap, it is a decoration of the window. You can disable them with yabai (i.e. window shadow). Or if you are adventerous you could try drawing the border on top of the window by using: https://github.com/FelixKratz/JankyBorders/issues/37#issuecomment-1871262622
