### ISSUE TITLE
border on the bottom part of window is faded

### ISSUE THREAD

**Issue by ellie-feng** [FelixKratz/JankyBorders#98]
Hello! I've noticed that when the bottom border of my active window is faded (not as vibrant or full as the top part of the window)? I run borders in conjunction with yabai but I've created a bordersrc file instead of bootstrapping in my yabairc file (as in yabai isn't aware? of borders. It's not an urgent matter but just something I've noticed, maybe something on my end?
![Screenshot 2024-05-29 at 22 25 51](https://github.com/FelixKratz/JankyBorders/assets/125713754/5bd32420-8c8d-4dd7-8ef3-65af5e84e33e)

**Comment by FelixKratz** [comment]
See #37
